""" Schemas for job management."""
from pydantic import BaseModel, ConfigDict, Field, HttpUrl 
from typing import Optional
from datetime import datetime
from app.db.models import JobSourceType

class JobExtractedData(BaseModel):
    """ Schema for extracted job data via llm processing."""
    title: Optional[str] = Field(None, description="Extracted job title", examples=["Software Engineer", "Senior Software Engineer"])
    company_name: Optional[str] = Field(None, description="Extracted company name", examples=["Tech Solutions Inc.", "Example Corp"])
    location: Optional[str] = Field(None, description="Extracted job location", examples=["San Francisco, CA or Remote", "New York, NY or Remote"])
    job_url: Optional[HttpUrl] = Field(None, description="URL of the job posting", examples=["https://example.com/jobs/123", "https://example.com/jobs/456"])
    date_posted: Optional[datetime] = Field(None, description="Date the job was posted", examples=["2023-01-01", "2023-01-02"])
    submission_deadline: Optional[datetime] = Field(None, description="Application submission deadline", examples=["2023-01-01", "2023-01-02"])
    hiring_manager_name: Optional[str] = Field(None, description="Name of the hiring manager, if available")

    model_config = ConfigDict(from_attributes=True, extra='allow')

class JobSourceData(BaseModel):
    """ Schema for job source information."""
    type: JobSourceType
    original_value: str = Field(description="Original input value: URL, raw text, or file path.")
    filename: Optional[str] = Field(None, description="Filename for file uploads.")
    mime_type: Optional[str] = Field(None, description="MIME type for file uploads.")

    model_config = ConfigDict(from_attributes=True, use_enum_values=True)

# --- Base Schema ---
class JobBase(BaseModel):
    """ Base schema for job data, reflecting the DB model.
        Defines the contract for representing a job in the system.
        Optimized for data structure and consistency.
    """
    source_data: JobSourceData
    raw_text: Optional[str] = Field(None, description="The processed raw text from the job source.")
    extracted_data: Optional[JobExtractedData] = Field(None, description="All structured data extracted from the job source or provided manually.")
    status: Optional[str] = Field(None, description="Processing status of the job (e.g., pending, processing, ready, error)", json_schema_extra={"examples": ["Ready"]})

    model_config = ConfigDict(from_attributes=True)

# --- Create Schema ---
class JobCreate(BaseModel):
    """ Schema for creating a new job from a specific source.
        This schema is used by the API endpoint to capture the initial job creation request.
        It does not contain fields that are generated by the system (like extracted_data or status).
    """
    source_type: JobSourceType
    source_value: str # For URL or TEXT, this is the content. For FILE, it's the initial filename.
    source_filename: Optional[str] = None
    source_mime_type: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)

# --- Update Schema ---
class JobUpdate(BaseModel):
    """Schema for updating the extracted fields or status of an existing job."""
    extracted_data: Optional[JobExtractedData] = Field(None, description="Updated structured data for the job.")
    status: Optional[str] = Field(None, description="Updated job processing status (e.g., Ready, Error)")

    model_config = ConfigDict(from_attributes=True)

# --- Response Schema ---
class JobResponse(JobBase):
    """ Schema for job response, includes IDs and timestamps.
        Defines the contract for job data returned to the client.
    """
    id: int
    user_id: int
    company_id: Optional[int] = None # From Job model

    time_created: datetime
    time_updated: datetime

    model_config = ConfigDict(from_attributes=True)