"""Add cover_letter_text column to CoverLetter

Revision ID: 2bdd44091ec3
Revises: 76cd377586ae
Create Date: 2025-05-06 11:14:33.265523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdd44091ec3'
down_revision: Union[str, None] = '76cd377586ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('cover_letter_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cover_letters', 'cover_letter_text')
    # ### end Alembic commands ###
