"""Add title and generation_options to CoverLetter table, remove template_name

Revision ID: 6d183593f7fc
Revises: 2bdd44091ec3
Create Date: 2025-05-06 13:01:17.998085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d183593f7fc'
down_revision: Union[str, None] = '2bdd44091ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('title', sa.String(), nullable=True))
    op.add_column('cover_letters', sa.Column('generation_options', sa.JSON(), nullable=True))
    op.drop_index('ix_cover_letters_template_name', table_name='cover_letters')
    op.create_index(op.f('ix_cover_letters_title'), 'cover_letters', ['title'], unique=False)
    op.drop_column('cover_letters', 'template_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('template_name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_cover_letters_title'), table_name='cover_letters')
    op.create_index('ix_cover_letters_template_name', 'cover_letters', ['template_name'], unique=False)
    op.drop_column('cover_letters', 'generation_options')
    op.drop_column('cover_letters', 'title')
    # ### end Alembic commands ###
