"""Add user_data column to users table

Revision ID: 744f49fc0e0e
Revises: 3bb79eb0f6d2
Create Date: 2025-06-24 15:49:43.968907

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "744f49fc0e0e"
down_revision: Union[str, None] = "3bb79eb0f6d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_data", sa.JSON(), nullable=True))
        batch_op.drop_index("ix_users_name")
        batch_op.drop_index("ix_users_surname")
        batch_op.drop_column("name")
        batch_op.drop_column("contact_info")
        batch_op.drop_column("surname")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("surname", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("contact_info", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=True))
        batch_op.create_index("ix_users_surname", ["surname"], unique=False)
        batch_op.create_index("ix_users_name", ["name"], unique=False)
        batch_op.drop_column("user_data")

    # ### end Alembic commands ###
