"""Remove redundant job_data column from jobs table

Revision ID: 76cd377586ae
Revises: f11a83c274fc
Create Date: 2025-05-05 16:03:03.007914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cd377586ae'
down_revision: Union[str, None] = 'f11a83c274fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_data', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
