"""Add sections JSON column and remove text column from CoverLetter

Revision ID: e4fe86992cbc
Revises: 
Create Date: 2025-05-05 11:23:59.816585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fe86992cbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('sections', sa.JSON(), nullable=True))
    op.drop_column('cover_letters', 'cover_letter_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('cover_letter_text', sa.VARCHAR(), nullable=True))
    op.drop_column('cover_letters', 'sections')
    # ### end Alembic commands ###
