"""Implement source-aware Job model structure

Revision ID: f11a83c274fc
Revises: e4fe86992cbc
Create Date: 2025-05-05 13:40:04.563756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11a83c274fc'
down_revision: Union[str, None] = 'e4fe86992cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema using batch mode for SQLite compatibility."""
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    
    # Explicitly drop the existing index before the batch operation
    op.drop_index('ix_jobs_title', table_name='jobs')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # Add new columns with server_default for NOT NULL constraints
        batch_op.add_column(sa.Column('source_type', sa.Enum('url', 'file', 'text', 'manual', name='jobsourcetype'), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('source_value', sa.Text(), nullable=False, server_default='<unknown>')) # Provide a sensible default
        batch_op.add_column(sa.Column('source_filename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_mime_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('job_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('hiring_manager', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('full_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True)) # Use server_default from model
        batch_op.add_column(sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True)) # Use server_default from model

        # Alter existing columns if needed (e.g., nullability change)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False) # Ensures user_id is NOT NULL

        # Create ALL required indices within the batch op
        batch_op.create_index(batch_op.f('ix_jobs_title'), ['title'], unique=False) # Re-create the title index
        batch_op.create_index(batch_op.f('ix_jobs_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

        # NOTE: We are NOT dropping the old 'job_data' column based on the model diff

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema using batch mode."""
    # ### commands auto generated by Alembic - adjusted for batch mode ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # Drop indices (removed ix_jobs_title)
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_company'))
        batch_op.drop_index(batch_op.f('ix_jobs_title'))

        # Revert column alterations
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True) # Revert user_id nullability

        # Drop added columns
        batch_op.drop_column('time_updated')
        batch_op.drop_column('time_created')
        batch_op.drop_column('full_description')
        batch_op.drop_column('status')
        batch_op.drop_column('hiring_manager')
        batch_op.drop_column('submission_deadline')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('job_url')
        batch_op.drop_column('source_mime_type')
        batch_op.drop_column('source_filename')
        batch_op.drop_column('source_value')
        batch_op.drop_column('source_type')

        # NOTE: We are NOT adding back the old 'job_data' column as it wasn't dropped

    # ### end Alembic commands ###
