"""Align User model with new schema

Revision ID: ff9498f91893
Revises: 744f49fc0e0e
Create Date: 2025-06-25 11:57:13.858404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff9498f91893"
down_revision: Union[str, None] = "744f49fc0e0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("surname", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("contact_info", sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f("ix_users_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_surname"), ["surname"], unique=False)
        batch_op.drop_column("user_data")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_data", sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_users_surname"))
        batch_op.drop_index(batch_op.f("ix_users_name"))
        batch_op.drop_column("contact_info")
        batch_op.drop_column("surname")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
