"""Rename cover_letter_text to text in CoverLetter model

Revision ID: 68fb234a41f5
Revises: 6a8b6e981743
Create Date: 2025-06-20 11:38:44.501036

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68fb234a41f5"
down_revision: Union[str, None] = "6a8b6e981743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("text", sa.Text(), nullable=True))
        batch_op.drop_column("cover_letter_text")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cover_letter_text", sa.TEXT(), nullable=True))
        batch_op.drop_column("text")

    # ### end Alembic commands ###
