"""Add llm_service_used to CoverLetter model

Revision ID: cd4c5b094275
Revises: f279166cf2ef
Create Date: 2025-06-23 13:35:50.798562

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd4c5b094275"
down_revision: Union[str, None] = "f279166cf2ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("llm_service_used", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cover_letters", schema=None) as batch_op:
        batch_op.drop_column("llm_service_used")

    # ### end Alembic commands ###
